services:
  pavs-app:
    container_name: pavs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./phenopackets.db:/app/phenopackets.db
      - ./data:/app/data
      - ./phenopackets:/app/phenopackets
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
